### ISSUE TITLE
Refactor hashmyjs.js:handleData

### ISSUE THREAD

**Issue by Berkmann18** [Berkmann18/hashmyjs#16]
I've selected [**hashmyjs.js:handleData**](https://github.com/Berkmann18/hashmyjs/blob/41dc581e909b6752949c30b88a9df1b521268b9a/src/hashmyjs.js#L176-L222) for refactoring, which is a unit of **34** lines of code and **4** parameters. Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Keep Unit Interfaces Small** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Limit the number of parameters per unit to at most 4.
- **Why**❓ 
Keeping the number of parameters low makes units easier to understand, test and reuse.
- **How** 🔧 
Reduce the number of parameters by grouping related parameters into objects. Alternatively, try extracting parts of units that require fewer parameters.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

**Comment by MichielCuijpers** [comment]
HI @Berkmann18, 

Thanks for you question, I need to explain a little about the way these refactoring candidates work. In that window we list the top 30 of your files, so also the files that are in the good quality profile. We allow you to choose which files you want to refactor based on your own understanding of the code base. Sometimes people leave very long or complex methods and compensate those by refactoring others. In any way we want to help you find that equilibrium where you fix just enough. We also want to help you stop 'gold-plating' code that is already compliant.

In your case the guideline is almost met, if you would select the hashmyjs.js.run (which has 5 parameters and not 4) for refactoring, you would tilt the score to a positive ✅ compliancy. Indeed refactoring the file hashmyjs.js:handleData with 4 parameters does not impact the overall maintainability heavily because 4 is in the good profile already. 

About your confusion, we could alter the template text to warn you that you are refactoring a candidate that is already in the clear, will check with development.

![schermafbeelding 2018-08-13 om 09 19 22](https://user-images.githubusercontent.com/18576001/44017877-34e24fb8-9eda-11e8-92e1-6b1feff7cfb4.jpg)

We put a default text in the issue, that describes the general guideline. I see how this can confuse developers when they miss the context of the other refactor candidates that were there at that time. With the generic text 'Addressing this will make our codebase more maintainable and improve' we strive to say that working on this file will improve the maintainability. In your case this file will not have a big impact tough. Hope this helps ?

**Comment by Berkmann18** [comment]
@MichielCuijpers Oh I see, thank you for clearing that up.
